---
# tasks file for ansible_role_pip

- name: "PIP | Ensure that python 2.7 is installed"
  yum:
    name: python
    state: present
  tags:
    - install
    - pip

- name: "PIP | Install python-pip"
  yum:
    name: python-pip
    state: present
  tags:
    - install
    - pip
